name: "Diff porcelain"

description: "Checks if the current branch is clean and with errors a custom message otherwise"

branding:
  icon: activity
  color: green

inputs:
  message:
    description: "Error message being used if changes are detected"
    required: true
    default: "Changes detected"
runs:
  using: "composite"
  steps:
    - name: Error if changes detected
      shell: bash
      run: |
        changes="$(git status --porcelain)"
        if [[ -n "$changes" ]]; then
          echo "${{ inputs.message }}"
          echo ""
          echo "Changed files:"
          echo "$changes"
          exit 1
        fi
